name: chem_nor
description: Dart package that finds relevant chemical compounds using AI(Gemini) and PubChem. Use it to level up your chemistry knowledge and chat with your Ai chemist!
version: 0.4.1
repository: https://github.com/mohammed-nor/ChemNOR-package
issue_tracker: https://github.com/mohammed-nor/ChemNOR-package/issues
homepage: https://github.com/mohammed-nor/ChemNOR-package
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  http: ^1.3.0
  intl: ^0.20.2


dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
