name: ChemNOR
description: A Dart package to find relevant chemical compounds using AI and PubChem.
version: 0.1.0
repository: https://github.com/mohammed-nor/ChemNOR-package
issue_tracker: https://github.com/mohammed-nor/ChemNOR-package/issues
homepage: https://github.com/mohammed-nor/ChemNOR-package
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  google_generative_ai: 0.4.6
  http: 1.1.0
  intl: 0.19.0

dev_dependencies:
  lints: 2.1.1
  test: 1.25.5
