/// Periodic table data and utilities.
class ElementData {
  /// Chemical symbol (e.g., 'H', 'He', 'Li')
  final String symbol;

  /// Full element name (e.g., 'Hydrogen', 'Helium', 'Lithium')
  final String name;

  /// Atomic number
  final int atomicNumber;

  /// Atomic mass in atomic mass units (u)
  final double atomicMass;

  /// Element category (e.g., 'noble gas', 'alkali metal')
  final String category;

  /// Period number in the periodic table
  final int period;

  /// Group number in the periodic table
  final int group;

  /// Electron configuration
  final String electronConfiguration;

  /// Electronegativity (Pauling scale)
  final double? electronegativity;

  /// Density at room temperature (g/cm³)
  final double? density;

  /// Melting point in Kelvin
  final double? meltingPoint;

  /// Boiling point in Kelvin
  final double? boilingPoint;

  /// Standard state at room temperature (solid, liquid, gas)
  final String standardState;

  ElementData({
    required this.symbol,
    required this.name,
    required this.atomicNumber,
    required this.atomicMass,
    required this.category,
    required this.period,
    required this.group,
    required this.electronConfiguration,
    this.electronegativity,
    this.density,
    this.meltingPoint,
    this.boilingPoint,
    required this.standardState,
  });
}

/// Periodic table with data for all elements
final periodicTable = <String, ElementData>{
  'H': ElementData(
    symbol: 'H',
    name: 'Hydrogen',
    atomicNumber: 1,
    atomicMass: 1.008,
    category: 'nonmetal',
    period: 1,
    group: 1,
    electronConfiguration: '1s¹',
    electronegativity: 2.20,
    density: 0.00008988,
    meltingPoint: 13.99,
    boilingPoint: 20.27,
    standardState: 'gas',
  ),
  'He': ElementData(
    symbol: 'He',
    name: 'Helium',
    atomicNumber: 2,
    atomicMass: 4.0026,
    category: 'noble gas',
    period: 1,
    group: 18,
    electronConfiguration: '1s²',
    electronegativity: null,
    density: 0.0001785,
    meltingPoint: 0.95,
    boilingPoint: 4.22,
    standardState: 'gas',
  ),
  'Li': ElementData(
    symbol: 'Li',
    name: 'Lithium',
    atomicNumber: 3,
    atomicMass: 6.94,
    category: 'alkali metal',
    period: 2,
    group: 1,
    electronConfiguration: '[He] 2s¹',
    electronegativity: 0.98,
    density: 0.534,
    meltingPoint: 453.65,
    boilingPoint: 1615,
    standardState: 'solid',
  ),
  'Be': ElementData(
    symbol: 'Be',
    name: 'Beryllium',
    atomicNumber: 4,
    atomicMass: 9.0122,
    category: 'alkaline earth metal',
    period: 2,
    group: 2,
    electronConfiguration: '[He] 2s²',
    electronegativity: 1.57,
    density: 1.85,
    meltingPoint: 1560,
    boilingPoint: 2742,
    standardState: 'solid',
  ),
  // Add more elements as needed...
  'O': ElementData(
    symbol: 'O',
    name: 'Oxygen',
    atomicNumber: 8,
    atomicMass: 15.999,
    category: 'nonmetal',
    period: 2,
    group: 16,
    electronConfiguration: '[He] 2s² 2p⁴',
    electronegativity: 3.44,
    density: 0.001429,
    meltingPoint: 54.36,
    boilingPoint: 90.20,
    standardState: 'gas',
  ),
  'C': ElementData(
    symbol: 'C',
    name: 'Carbon',
    atomicNumber: 6,
    atomicMass: 12.011,
    category: 'nonmetal',
    period: 2,
    group: 14,
    electronConfiguration: '[He] 2s² 2p²',
    electronegativity: 2.55,
    density: 2.267,
    meltingPoint: 3823,
    boilingPoint: 4300,
    standardState: 'solid',
  ),
  'N': ElementData(
    symbol: 'N',
    name: 'Nitrogen',
    atomicNumber: 7,
    atomicMass: 14.007,
    category: 'nonmetal',
    period: 2,
    group: 15,
    electronConfiguration: '[He] 2s² 2p³',
    electronegativity: 3.04,
    density: 0.0012506,
    meltingPoint: 63.15,
    boilingPoint: 77.36,
    standardState: 'gas',
  ),
  'B': ElementData(
    symbol: 'B',
    name: 'Boron',
    atomicNumber: 5,
    atomicMass: 10.81,
    category: 'metalloid',
    period: 2,
    group: 13,
    electronConfiguration: '[He] 2s² 2p¹',
    electronegativity: 2.04,
    density: 2.37,
    meltingPoint: 2349,
    boilingPoint: 4200,
    standardState: 'solid',
  ),
  'F': ElementData(
    symbol: 'F',
    name: 'Fluorine',
    atomicNumber: 9,
    atomicMass: 18.998,
    category: 'halogen',
    period: 2,
    group: 17,
    electronConfiguration: '[He] 2s² 2p⁵',
    electronegativity: 3.98,
    density: 0.001696,
    meltingPoint: 53.53,
    boilingPoint: 85.03,
    standardState: 'gas',
  ),
  'Ne': ElementData(
    symbol: 'Ne',
    name: 'Neon',
    atomicNumber: 10,
    atomicMass: 20.180,
    category: 'noble gas',
    period: 2,
    group: 18,
    electronConfiguration: '[He] 2s² 2p⁶',
    electronegativity: null,
    density: 0.0008999,
    meltingPoint: 24.56,
    boilingPoint: 27.07,
    standardState: 'gas',
  ),
  // Period 3
  'Na': ElementData(
    symbol: 'Na',
    name: 'Sodium',
    atomicNumber: 11,
    atomicMass: 22.990,
    category: 'alkali metal',
    period: 3,
    group: 1,
    electronConfiguration: '[Ne] 3s¹',
    electronegativity: 0.93,
    density: 0.968,
    meltingPoint: 370.87,
    boilingPoint: 1156,
    standardState: 'solid',
  ),
  'Mg': ElementData(
    symbol: 'Mg',
    name: 'Magnesium',
    atomicNumber: 12,
    atomicMass: 24.305,
    category: 'alkaline earth metal',
    period: 3,
    group: 2,
    electronConfiguration: '[Ne] 3s²',
    electronegativity: 1.31,
    density: 1.738,
    meltingPoint: 923,
    boilingPoint: 1363,
    standardState: 'solid',
  ),
  'Al': ElementData(
    symbol: 'Al',
    name: 'Aluminum',
    atomicNumber: 13,
    atomicMass: 26.982,
    category: 'post-transition metal',
    period: 3,
    group: 13,
    electronConfiguration: '[Ne] 3s² 3p¹',
    electronegativity: 1.61,
    density: 2.7,
    meltingPoint: 933.47,
    boilingPoint: 2792,
    standardState: 'solid',
  ),
  'Si': ElementData(
    symbol: 'Si',
    name: 'Silicon',
    atomicNumber: 14,
    atomicMass: 28.085,
    category: 'metalloid',
    period: 3,
    group: 14,
    electronConfiguration: '[Ne] 3s² 3p²',
    electronegativity: 1.90,
    density: 2.3296,
    meltingPoint: 1687,
    boilingPoint: 3538,
    standardState: 'solid',
  ),
  'P': ElementData(
    symbol: 'P',
    name: 'Phosphorus',
    atomicNumber: 15,
    atomicMass: 30.974,
    category: 'nonmetal',
    period: 3,
    group: 15,
    electronConfiguration: '[Ne] 3s² 3p³',
    electronegativity: 2.19,
    density: 1.82,
    meltingPoint: 317.3,
    boilingPoint: 553.6,
    standardState: 'solid',
  ),
  'S': ElementData(
    symbol: 'S',
    name: 'Sulfur',
    atomicNumber: 16,
    atomicMass: 32.06,
    category: 'nonmetal',
    period: 3,
    group: 16,
    electronConfiguration: '[Ne] 3s² 3p⁴',
    electronegativity: 2.58,
    density: 2.067,
    meltingPoint: 388.36,
    boilingPoint: 717.87,
    standardState: 'solid',
  ),
  'Cl': ElementData(
    symbol: 'Cl',
    name: 'Chlorine',
    atomicNumber: 17,
    atomicMass: 35.45,
    category: 'halogen',
    period: 3,
    group: 17,
    electronConfiguration: '[Ne] 3s² 3p⁵',
    electronegativity: 3.16,
    density: 0.003214,
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    standardState: 'gas',
  ),
  'Ar': ElementData(
    symbol: 'Ar',
    name: 'Argon',
    atomicNumber: 18,
    atomicMass: 39.948,
    category: 'noble gas',
    period: 3,
    group: 18,
    electronConfiguration: '[Ne] 3s² 3p⁶',
    electronegativity: null,
    density: 0.0017837,
    meltingPoint: 83.80,
    boilingPoint: 87.30,
    standardState: 'gas',
  ),
  // Period 4
  'K': ElementData(
    symbol: 'K',
    name: 'Potassium',
    atomicNumber: 19,
    atomicMass: 39.098,
    category: 'alkali metal',
    period: 4,
    group: 1,
    electronConfiguration: '[Ar] 4s¹',
    electronegativity: 0.82,
    density: 0.856,
    meltingPoint: 336.53,
    boilingPoint: 1032,
    standardState: 'solid',
  ),
  'Ca': ElementData(
    symbol: 'Ca',
    name: 'Calcium',
    atomicNumber: 20,
    atomicMass: 40.078,
    category: 'alkaline earth metal',
    period: 4,
    group: 2,
    electronConfiguration: '[Ar] 4s²',
    electronegativity: 1.00,
    density: 1.55,
    meltingPoint: 1115,
    boilingPoint: 1757,
    standardState: 'solid',
  ),
  'Sc': ElementData(
    symbol: 'Sc',
    name: 'Scandium',
    atomicNumber: 21,
    atomicMass: 44.956,
    category: 'transition metal',
    period: 4,
    group: 3,
    electronConfiguration: '[Ar] 3d¹ 4s²',
    electronegativity: 1.36,
    density: 2.985,
    meltingPoint: 1814,
    boilingPoint: 3109,
    standardState: 'solid',
  ),
  'Ti': ElementData(
    symbol: 'Ti',
    name: 'Titanium',
    atomicNumber: 22,
    atomicMass: 47.867,
    category: 'transition metal',
    period: 4,
    group: 4,
    electronConfiguration: '[Ar] 3d² 4s²',
    electronegativity: 1.54,
    density: 4.507,
    meltingPoint: 1941,
    boilingPoint: 3560,
    standardState: 'solid',
  ),
  'V': ElementData(
    symbol: 'V',
    name: 'Vanadium',
    atomicNumber: 23,
    atomicMass: 50.942,
    category: 'transition metal',
    period: 4,
    group: 5,
    electronConfiguration: '[Ar] 3d³ 4s²',
    electronegativity: 1.63,
    density: 6.11,
    meltingPoint: 2183,
    boilingPoint: 3680,
    standardState: 'solid',
  ),
  'Cr': ElementData(
    symbol: 'Cr',
    name: 'Chromium',
    atomicNumber: 24,
    atomicMass: 51.996,
    category: 'transition metal',
    period: 4,
    group: 6,
    electronConfiguration: '[Ar] 3d⁵ 4s¹',
    electronegativity: 1.66,
    density: 7.15,
    meltingPoint: 2180,
    boilingPoint: 2944,
    standardState: 'solid',
  ),
  'Mn': ElementData(
    symbol: 'Mn',
    name: 'Manganese',
    atomicNumber: 25,
    atomicMass: 54.938,
    category: 'transition metal',
    period: 4,
    group: 7,
    electronConfiguration: '[Ar] 3d⁵ 4s²',
    electronegativity: 1.55,
    density: 7.44,
    meltingPoint: 1519,
    boilingPoint: 2334,
    standardState: 'solid',
  ),
  'Fe': ElementData(
    symbol: 'Fe',
    name: 'Iron',
    atomicNumber: 26,
    atomicMass: 55.845,
    category: 'transition metal',
    period: 4,
    group: 8,
    electronConfiguration: '[Ar] 3d⁶ 4s²',
    electronegativity: 1.83,
    density: 7.874,
    meltingPoint: 1811,
    boilingPoint: 3134,
    standardState: 'solid',
  ),
  'Co': ElementData(
    symbol: 'Co',
    name: 'Cobalt',
    atomicNumber: 27,
    atomicMass: 58.933,
    category: 'transition metal',
    period: 4,
    group: 9,
    electronConfiguration: '[Ar] 3d⁷ 4s²',
    electronegativity: 1.88,
    density: 8.90,
    meltingPoint: 1768,
    boilingPoint: 3200,
    standardState: 'solid',
  ),
  'Ni': ElementData(
    symbol: 'Ni',
    name: 'Nickel',
    atomicNumber: 28,
    atomicMass: 58.693,
    category: 'transition metal',
    period: 4,
    group: 10,
    electronConfiguration: '[Ar] 3d⁸ 4s²',
    electronegativity: 1.91,
    density: 8.908,
    meltingPoint: 1728,
    boilingPoint: 3186,
    standardState: 'solid',
  ),
  'Cu': ElementData(
    symbol: 'Cu',
    name: 'Copper',
    atomicNumber: 29,
    atomicMass: 63.546,
    category: 'transition metal',
    period: 4,
    group: 11,
    electronConfiguration: '[Ar] 3d¹⁰ 4s¹',
    electronegativity: 1.90,
    density: 8.96,
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    standardState: 'solid',
  ),
  'Zn': ElementData(
    symbol: 'Zn',
    name: 'Zinc',
    atomicNumber: 30,
    atomicMass: 65.38,
    category: 'transition metal',
    period: 4,
    group: 12,
    electronConfiguration: '[Ar] 3d¹⁰ 4s²',
    electronegativity: 1.65,
    density: 7.14,
    meltingPoint: 692.88,
    boilingPoint: 1180,
    standardState: 'solid',
  ),
  'Ga': ElementData(
    symbol: 'Ga',
    name: 'Gallium',
    atomicNumber: 31,
    atomicMass: 69.723,
    category: 'post-transition metal',
    period: 4,
    group: 13,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p¹',
    electronegativity: 1.81,
    density: 5.91,
    meltingPoint: 302.91,
    boilingPoint: 2477,
    standardState: 'solid',
  ),
  'Ge': ElementData(
    symbol: 'Ge',
    name: 'Germanium',
    atomicNumber: 32,
    atomicMass: 72.630,
    category: 'metalloid',
    period: 4,
    group: 14,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p²',
    electronegativity: 2.01,
    density: 5.323,
    meltingPoint: 1211.4,
    boilingPoint: 3106,
    standardState: 'solid',
  ),
  'As': ElementData(
    symbol: 'As',
    name: 'Arsenic',
    atomicNumber: 33,
    atomicMass: 74.922,
    category: 'metalloid',
    period: 4,
    group: 15,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p³',
    electronegativity: 2.18,
    density: 5.727,
    meltingPoint: 1090,
    boilingPoint: 887,
    standardState: 'solid',
  ),
  'Se': ElementData(
    symbol: 'Se',
    name: 'Selenium',
    atomicNumber: 34,
    atomicMass: 78.971,
    category: 'nonmetal',
    period: 4,
    group: 16,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁴',
    electronegativity: 2.55,
    density: 4.81,
    meltingPoint: 494,
    boilingPoint: 958,
    standardState: 'solid',
  ),
  'Br': ElementData(
    symbol: 'Br',
    name: 'Bromine',
    atomicNumber: 35,
    atomicMass: 79.904,
    category: 'halogen',
    period: 4,
    group: 17,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁵',
    electronegativity: 2.96,
    density: 3.12,
    meltingPoint: 265.8,
    boilingPoint: 332,
    standardState: 'liquid',
  ),
  'Kr': ElementData(
    symbol: 'Kr',
    name: 'Krypton',
    atomicNumber: 36,
    atomicMass: 83.798,
    category: 'noble gas',
    period: 4,
    group: 18,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁶',
    electronegativity: null,
    density: 0.003733,
    meltingPoint: 115.79,
    boilingPoint: 119.93,
    standardState: 'gas',
  ),
};

/// Utility class for periodic table operations
class PeriodicTable {
  /// Gets an element by its symbol
  static ElementData? getBySymbol(String symbol) {
    return periodicTable[symbol];
  }

  /// Gets an element by its atomic number
  static ElementData? getByAtomicNumber(int atomicNumber) {
    return periodicTable.values.firstWhere((element) => element.atomicNumber == atomicNumber, orElse: () => throw StateError('No element with atomic number $atomicNumber'));
  }

  /// Gets all elements in a specific group
  static List<ElementData> getByGroup(int group) {
    return periodicTable.values.where((element) => element.group == group).toList();
  }

  /// Gets all elements in a specific period
  static List<ElementData> getByPeriod(int period) {
    return periodicTable.values.where((element) => element.period == period).toList();
  }

  /// Gets all elements in a specific category
  static List<ElementData> getByCategory(String category) {
    return periodicTable.values.where((element) => element.category.toLowerCase() == category.toLowerCase()).toList();
  }

  /// Gets elements with atomic mass in the specified range
  static List<ElementData> getByMassRange(double min, double max) {
    return periodicTable.values.where((element) => element.atomicMass >= min && element.atomicMass <= max).toList();
  }

  /// Gets elements with the specified standard state
  static List<ElementData> getByStandardState(String state) {
    return periodicTable.values.where((element) => element.standardState.toLowerCase() == state.toLowerCase()).toList();
  }
}
